[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install Flask==3.0.0",
  "pip install Flask-Cors==4.0.0",
  "pip install yt-dlp"
]

[start]
cmd = "python app.py"